deployment:
  tasks:
    # Activar Node.js v20 para el front (venv propio, opcional)
    - /bin/echo "→ Activating Node venv"
    - source /home/indoff7/nodevenv/indoffpro_front_build/20/bin/activate

    # Entrar al repo clonado
    - /bin/echo "→ Entering repo"
    - cd /home/indoff7/indoffpro_front

    # Instalar dependencias y compilar
    - /bin/echo "→ Installing dependencies"
    - npm ci
    - /bin/echo "→ Building production bundle"
    - npm run build

    # Copiar build al docroot de indoffpro.com
    - /bin/echo "→ Deploying to docroot"
    - /bin/rsync -a --delete dist/ /home/indoff7/indoffpro.com/

    # SPA fallback para React Router (solo si no existe .htaccess)
    - /bin/test -f /home/indoff7/indoffpro.com/.htaccess || /bin/bash -lc 'cat > /home/indoff7/indoffpro.com/.htaccess << "EOF"
      RewriteEngine On
      RewriteBase /
      RewriteCond %{REQUEST_FILENAME} -f [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^ - [L]
      RewriteRule . /index.html [L]
      EOF'
