deployment:
  tasks:
    - /bin/echo "→ Deploying prebuilt dist"
    - /bin/rsync -a --delete /home/indoff7/indoffpro_front/dist/ /home/indoff7/indoffpro.com/
    - /bin/bash -lc '[ -f /home/indoff7/indoffpro.com/.htaccess ] || echo -e "RewriteEngine On\nRewriteRule . /index.html [L]" > /home/indoff7/indoffpro.com/.htaccess'
    