deployment:
  tasks:
    - /bin/echo "→ Activating Node venv"
    - source /home/indoff7/nodevenv/indoffpro_front_build/20/bin/activate
    - /bin/echo "→ Entering repo"
    - cd /home/indoff7/indoffpro_front
    - /bin/echo "→ Installing deps"
    - npm ci
    - /bin/echo "→ Building"
    - npm run build
    - /bin/echo "→ Deploying dist/ to docroot"
    - rsync -a --delete dist/ /home/indoff7/indoffpro.com/
    - /bin/test -f /home/indoff7/indoffpro.com/.htaccess || /bin/bash -lc 'cat > /home/indoff7/indoffpro.com/.htaccess << "EOF"
      RewriteEngine On
      RewriteRule . /index.html [L]
      EOF'
