deployment:
  tasks:
    - /bin/bash -lc '
        set -e
        echo "→ Activating Node venv";
        source /home/indoff7/nodevenv/indoffpro_front_build/20/bin/activate;

        echo "→ Entering repo";
        cd /home/indoff7/indoffpro_front;

        echo "→ Node/NPM versions";
        node -v && npm -v;

        echo "→ Installing deps (npm ci)";
        npm ci;

        echo "→ Building";
        npm run build;

        echo "→ Deploying dist/ to docroot";
        rsync -a --delete dist/ /home/indoff7/indoffpro.com/;

        echo "→ Ensuring SPA .htaccess";
        if [ ! -f /home/indoff7/indoffpro.com/.htaccess ]; then
          cat > /home/indoff7/indoffpro.com/.htaccess << "EOF"
          RewriteEngine On
          RewriteBase /
          RewriteCond %{REQUEST_FILENAME} -f [OR]
          RewriteCond %{REQUEST_FILENAME} -d
          RewriteRule ^ - [L]
          RewriteRule . /index.html [L]
          <IfModule mod_expires.c>
            ExpiresActive On
            ExpiresByType text/html "access plus 0 seconds"
            ExpiresByType text/css "access plus 7 days"
            ExpiresByType application/javascript "access plus 7 days"
            ExpiresByType image/webp "access plus 30 days"
            ExpiresByType image/png "access plus 30 days"
            ExpiresByType image/jpeg "access plus 30 days"
          </IfModule>
          EOF
        fi

        echo "✓ Done"
      '
